version: '3'
services:

  redis:
    image: redis:7.0.5
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"

  elastic:
    image: elasticsearch:8.5.2
    container_name: elastic
    restart: always
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - ./elastic_search_data_test:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - "9200"

  fastapi:
    build: fastapi-solution
    container_name: fastapi
    image: fastapi_image
    restart: always
    depends_on:
      - elastic
      - redis
    volumes:
      - ./fastapi-solution/src:/opt/app
    env_file:
      - .env-example
    ports:
      - "8000:8000"
    expose:
      - "8000"

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - fastapi
    ports:
      - "80:80"

  test_service:
    image: fastapi_image
    container_name: test_service
    stdin_open: true
    tty: true

    volumes:
      - ./tests/functional/logs:/opt/app/functional/logs
      - ./tests:/opt/app
    entrypoint: >
      sh -c "python functional/utils/wait_for_es.py
      && python functional/utils/wait_for_redis.py
      && pytest functional/src"
    env_file:
      - .env-example
    environment:
      - PYTHONPATH=/opt/app/functional:$PYTHONPATH
    depends_on:
      - fastapi
      - nginx
      - elastic
      - redis
